# Generated by Django 2.2.6 on 2020-01-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=50, verbose_name='Имя животного')),
                ('animal_class', models.CharField(max_length=30, verbose_name='Тип животного')),
                ('animal_description', models.TextField(verbose_name='Описание животного')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('animal_sex', models.CharField(max_length=20, verbose_name='Пол')),
                ('animal_age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('image_num', models.IntegerField(default=0, verbose_name='Номер картинки')),
            ],
        ),
    ]
