# Generated by Django 2.2.6 on 2020-01-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_num',
        ),
        migrations.AddField(
            model_name='animal',
            name='model_pic',
            field=models.ImageField(default='static/', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='animal',
            name='vk_url',
            field=models.CharField(default='lol', max_length=40, verbose_name='Ссылка вк'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_description',
            field=models.CharField(max_length=60, verbose_name='Описание животного'),
        ),
    ]
